import { Inter } from 'next/font/google';
import './globals.scss';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { ConfigProvider } from 'antd';
import theme from '@/theme/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <ConfigProvider theme={theme}>{children}</ConfigProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
